### ISSUE TITLE
Tried to run but no respond

### ISSUE THREAD

**Issue by abdulbadii** [fkmclane/mkusb#2]
Ran on:
`$ sudo mkusb
`
as it showed an only USB's sdb in list, its cursor was ready on OK button but that's it
it can't respond the selected OK to run further

Please help guide to the solution

**Comment by lilyinstarlight** [comment]
You can use the spacebar to select which USB device and then hit return to click OK

It uses [dialog](https://invisible-island.net/dialog/dialog.html) internally

**Comment by abdulbadii** [comment]
Excellent

likely from now, asking more technically, if you don't mind sincerely help me

what iso() recursive function do and which code requires or invokes it ?
can't find any such code line.. so confusing me

**Comment by lilyinstarlight** [comment]
You can make distro files that implicitly get sourced to provide info to those functions. See https://github.com/lilyinstarlight/mkusb/blob/main/distros

To be honest, you might have a much better time with something like ventoy (https://www.ventoy.net/) compared to this project. It's pretty much automatic compared to the effort you need for this tool (although it didn't exist when I wrote this tool)

**Comment by abdulbadii** [comment]
???
why aren't we just so thankful to God bestowing, entrusting us knowledges now, which we'd make use of

honestly I'm very slow thinker
you meant iso() function would never be invoked in mkusb shell script, but by another, sometimes somehow in process ?
